name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (ci with fallback)
        run: |
          npm ci || npm install

      - name: Build
        run: npm run build

      - name: Start app (background)
        run: |
          nohup npm start &
          echo $! > app.pid
        env:
          PORT: 3000
        shell: bash

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:3000 >/dev/null; then
              echo "App is up"; exit 0;
            fi
            echo "Waiting for app... ($i)"; sleep 2;
          done
          echo "App failed to start in time"; exit 1
        shell: bash

      - name: Stop app
        if: always()
        run: |
          if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
        shell: bash
